language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
    directories:
        - "~/.platformio"

install:
  - travis_retry pip install -r requirements-dev.txt



  - travis_retry pip install -U platformio adafruit-gpio
    #
    # Libraries from PlatformIO Library Registry:
    #
    # http://platformio.org/lib/show/19/Adafruit-DHT
  - platformio lib -g install 19

  - tree

script:
  - coverage run -m nose2.__main__ -v
after_success:
  - coveralls
addons:
    code_climate:
        repo_token: 80742566fc527b8f5a6f906a07b65ed9cd221de12fc4e3cd447275196f448ef6
